---
author: Eygló Ástþórsdóttir og Helga Björg Helgadóttir
date: 19. feb 2025
title: "fyrra_verkefni"
output: rmdformats::readthedown
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
```

```{r}
library(tidyverse)  # Fyrir gagnavinnslu
library(readr)      # Fyrir gagnainnlestur
library(dplyr)
```

## HLUTI 1
### a)
```{r}
eh <- read_csv("https://ahj.hi.is/survey_results_public_rev.csv")
```

### b)
```{r}
eh <- eh %>%
  filter(MainBranch == "I am a developer by profession" &
         Employment == "Employed, full-time")
```

### c)
```{r}
nrow(eh)  # Telur fjölda lína eftir síun
table(eh$MainBranch)  # Sýnir tíðnidreifingu í MainBranch
table(eh$Employment)  # Sýnir tíðnidreifingu í Employment

eh$years_before_pro <- eh$YearsCode - eh$YearsCodePro

summary(abs(eh$years_before_pro))
eh %>% filter(years_before_pro < 0) %>% select(YearsCode, YearsCodePro, years_before_pro)

```

### d
```{r}
# Remove extra text in Currency column
eh$Currency <- substr(eh$Currency, 1, 3)

# Keep only salaries reported in EUR or USD
eh <- eh %>% filter(Currency %in% c("EUR", "USD"))

```

### e)
```{r}
# Ensure CompTotal is numeric
eh$CompTotal <- as.numeric(eh$CompTotal)

# Remove NAs
eh <- eh %>% filter(!is.na(CompTotal))

# Compute IQR to detect outliers
Q1 <- quantile(eh$CompTotal, 0.25, na.rm = TRUE)
Q3 <- quantile(eh$CompTotal, 0.75, na.rm = TRUE)
IQR_value <- Q3 - Q1
lower_bound <- Q1 - 1.5 * IQR_value
upper_bound <- Q3 + 1.5 * IQR_value

# Filter out outliers
eh <- eh %>% filter(CompTotal >= lower_bound & CompTotal <= upper_bound)

# Check new salary summary
summary(eh$CompTotal)

```

### f)
```{r}
eh$CompTotalUSD <- ifelse(eh$Currency == "USD", eh$CompTotal,
                          ifelse(eh$Currency == "EUR", eh$CompTotal * 1.08, NA))  

summary(eh$CompTotalUSD)
eh %>% select(Currency, CompTotal, CompTotalUSD) %>% head(10)

```

### g)
```{r}
# Count number of responses per country
country_counts <- eh %>%
  count(Country, sort = TRUE)

# Get the top 10 countries
top_10_countries <- head(country_counts, 10)

# Display results
top_10_countries

```

### h)

### i)

### j)


## HLUTI 2
### k)

### l)

### m)

### n)

### o)


## HLUTI 3
### p)

### q)

### r)

